In [1]:
import numpy as np
import pandas as pd
import matplotlib .pyplot as plt
import seaborn as sns
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split


In [2]:
df=pd.read_csv("winequality-red.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.corr

<bound method DataFrame.corr of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df['quality'].unique()

In [ ]:
sns.pairplot(df)

In [ ]:
df.describe()

In [ ]:
sns.heatmap(df.isnull())

In [ ]:
df['pH'].plot.box()

In [ ]:
df['free sulfur dioxide'].plot.box()

In [ ]:
df['residual sugar'].plot.box()

In [ ]:
df['fixed acidity'].plot.box()

In [ ]:
df.plot(kind='box',subplots=True,layout=(2,6))
plt.show()

In [ ]:
from collections import Counter
Counter(df['quality'])

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='fixed acidity',data=df)

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='citric acid',data=df)

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='residual sugar',data=df)

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='fixed acidity',data=df)

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='chlorides',data=df)

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='free sulfur dioxide',data=df)

In [ ]:
fig=plt.figure(figsize=(5,6))
sns.barplot(x='quality',y='alcohol',data=df)

In [ ]:
#Preprocessing Data for performing ML Algorithm
bins=(2,6.5,8)
group_names=['bad','good']
df['quality']=pd.cut(df['quality'],bins=bins,labels=group_names)

In [ ]:
%matplolib inline
df['quality'].values.counts()

In [ ]:
sns.countplot(df['quality'])

In [ ]:
X=df.drop('quality',axis=1)
Y=df['quality']

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import confusion_matrix,classification_report


In [ ]:
sc=StandardScaler()

In [ ]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [ ]:
#RandomForest Classifier
rfc=RandomForestClassifier(n_estimators=200)
rfc.fit(X_train,Y_train)
pred_rfc=rfc.predict(X_test)

In [67]:
rfc_conf_matrix=confusion_matrix(Y_test,rfc_predict)
rfc_acc_score=accuracy_score(Y_test,rfc_predict)
print(rfc_conf_matrix)
print(rfc_acc_score*100)
print(classification_report(Y_test,pred_rfc))

[[264   9]
 [ 35  12]]
86.25
              precision    recall  f1-score   support

         bad       0.89      0.96      0.93       273
        good       0.62      0.34      0.44        47

    accuracy                           0.87       320
   macro avg       0.75      0.65      0.68       320
weighted avg       0.85      0.87      0.86       320



Random forest gives the accuracy of 89%

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import warnings
warnings.filterwarnings('ignore')

In [ ]:
print(confusion_matrix(Y_test,pred_rfc))

Stochastic Gradient Decent Classifier

In [ ]:
sgd=SGDClassifier(penalty=None)
sgd.fit(X_train,Y_train)
pred_sgd=sgd.predict(X_test)

In [ ]:
print(classification_report(Y_test,pred_sgd))

Accuracy=87% using stochastic gradient decent classifier

In [ ]:
print(confusion_matrix(Y_test,pred_sgd))

Support Vector Classifier

In [68]:
svc=SVC()
svc.fit(X_train,Y_train)
pred_svc=svc.predict(X_test)

In [69]:
print(classification_report(Y_test,pred_svc))

              precision    recall  f1-score   support

         bad       0.88      0.98      0.93       273
        good       0.71      0.26      0.37        47

    accuracy                           0.88       320
   macro avg       0.80      0.62      0.65       320
weighted avg       0.86      0.88      0.85       320



support vector classifier gets 86%

try to Increase Accuracy of modrls

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
#Finding best parametr for our svc model
param={
    'C':[0.1,0.8,0.9,1,1.1,1.2,1.3,1.4],
    'kernal':['linear','rbf'],
    'gamma':[0,0.8,0.9,1,1.1,1.2,1.3,1.4]
}
grid_svc=GridSearchCV(svc,param_grid=param,scoring='accuracy',cv=10)

In [ ]:
grid_svc.fit(X_train,Y_train)

Cross Validation Score for random forest and SGD

In [ ]:
rfc_eval=cross_val_score(estimator=rfc,X=X_train,y=Y_train,cv=10)
rfc.eval.mean()

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score

In [55]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr_predict=lr.predict(X_test)

In [56]:
lr_conf_matrix=confusion_matrix(Y_test,lr_predict)
lr_acc_score=accuracy_score(Y_test,lr_predict)
print(lr_conf_matrix)
print(lr_acc_score*100)

[[268   5]
 [ 35  12]]
87.5


now using Decision Tree cllsifier

In [58]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,Y_train)
dt_predict=dt.predict(X_test)

In [59]:
dt_conf_matrix=confusion_matrix(Y_test,dt_predict)
dt_acc_score=accuracy_score(Y_test,dt_predict)
print(dt_conf_matrix)
print(dt_acc_score*100)

[[249  24]
 [ 27  20]]
84.0625


Lesser accuracy with DecionTree Lets use GaussianNB

In [60]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,Y_train)
nb_predict=nb.predict(X_test)

In [61]:
nb_conf_matrix=confusion_matrix(Y_test,nb_predict)
nb_acc_score=accuracy_score(Y_test,nb_predict)
print(nb_conf_matrix)
print(nb_acc_score*100)

[[238  35]
 [ 12  35]]
85.3125


So we can see that the svc and the RandomForest gives us good prediction and accuracy for the Wine 
classification Problem.